// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
  apiKey: 'AIzaSyAm550AcMW8G1lzxDQhcb7B7PM-eB7WFkM',
  appId: '1:95078654469:web:e0ab007ae5f05a3d1f326c',
  messagingSenderId: '95078654469',
  projectId: 'cal-ai-3f300',
  storageBucket: 'cal-ai-3f300.firebasestorage.app',
  authDomain: 'cal-ai-3f300.firebaseapp.com',
  measurementId: 'G-HWKR7FFCFS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKSVWTjeu-g3J4rSWKFAY9l7QYG0XlZXo',
    appId: '1:95078654469:android:addffe48ff57d70a1f326c',
    messagingSenderId: '95078654469',
    projectId: 'cal-ai-3f300',
    storageBucket: 'cal-ai-3f300.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeKs5HwPIGum93S7lClBdYLgE9c7J-5qE',
    appId: '1:95078654469:ios:6f1a1b391526dab21f326c',
    messagingSenderId: '95078654469',
    projectId: 'cal-ai-3f300',
    storageBucket: 'cal-ai-3f300.firebasestorage.app',
    iosBundleId: 'com.calai.app',
  );
}